apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - my-agentset.yaml

openapi:
  path: https://raw.githubusercontent.com/kynoproj/kynomesh/main/api/json-schema/schema.json

patches:
  - patch: |-
      apiVersion: kynomesh.kyno.sh/v1alpha1
      kind: AgentSet
      metadata:
        name: my-agentset
      spec:
        agents:
          - name: researcher
            container:
              imagePullPolicy: Never
          - name: worker
            container:
              env:
                - name: foo
                  value: bar
