apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kynomesh-webhook-sa.yaml
- rbac
- kynomesh-webhook-deployment.yaml
- kynomesh-webhook-service.yaml

namespace: kynomesh-system

images:
  - name: quay.io/kynoproj/kynomesh
    newTag: latest
