site_name: Kynomesh - Distributed multi-agent orchestration
repo_url: https://github.com/kynoproj/kynomesh
edit_uri: edit/main/docs/
strict: true
theme:
  name: material
  favicon: assets/kyno04.svg
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/kyno04-white.svg
  palette:
    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.tabs.link
extra:
  version:
    provider: mike
    default: stable
  analytics:
    provider: google
    property: G-WD91ZWL6XY
extra_css:
  - assets/extra.css
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: README.md
  - Getting Started:
      - quick-start.md
  - User Guide:
      - Core Concepts:
          - Overview: "core-concepts/overview.md"
          - core-concepts/agentset.md
          - core-concepts/agentdeploy.md
      - Reference:
          - Autoscaling: "user-guide/reference/autoscaling.md"
          - Rate limiting: "user-guide/reference/rate-limiting.md"
          - GPU: "user-guide/reference/gpu.md"
          - Configuration:
              - Labels And Annotations: "user-guide/reference/configuration/labels-and-annotations.md"
              - Environment Variables: "user-guide/reference/configuration/environment-variables.md"
              - Container Resources: "user-guide/reference/configuration/container-resources.md"
              - Volumes: "user-guide/reference/configuration/volumes.md"
              - Init Containers: "user-guide/reference/configuration/init-containers.md"
              - Sidecar Containers: "user-guide/reference/configuration/sidecar-containers.md"
              - Liveness And Readiness: "user-guide/reference/configuration/liveness-and-readiness.md"
              - AgentSet Customization: "user-guide/reference/configuration/agentset-customization.md"
              - Rolling Update: "user-guide/reference/configuration/rolling-update.md"
              - Dynamic Resource Allocation: "user-guide/reference/configuration/dra.md"
              - Running On Istio: "user-guide/reference/configuration/istio.md"
          - APIs.md
  - Operator Manual:
      - Releases ⧉: "operations/releases.md"
      - operations/installation.md
      - operations/metrics.md
  - Contributor Guide:
      - development/development.md
      - Specifications:
          - development/specifications/agent-discovery.md
          - development/specifications/external-agents.md
      - development/debugging.md
      - development/static-code-analysis.md
      - development/releasing.md
