/*
Copyright 2026 The Kynoproj Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	kynomeshv1alpha1 "github.com/kynoproj/kynomesh/pkg/apis/kynomesh/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AgentSetLister helps list AgentSets.
// All objects returned here must be treated as read-only.
type AgentSetLister interface {
	// List lists all AgentSets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kynomeshv1alpha1.AgentSet, err error)
	// AgentSets returns an object that can list and get AgentSets.
	AgentSets(namespace string) AgentSetNamespaceLister
	AgentSetListerExpansion
}

// agentSetLister implements the AgentSetLister interface.
type agentSetLister struct {
	listers.ResourceIndexer[*kynomeshv1alpha1.AgentSet]
}

// NewAgentSetLister returns a new AgentSetLister.
func NewAgentSetLister(indexer cache.Indexer) AgentSetLister {
	return &agentSetLister{listers.New[*kynomeshv1alpha1.AgentSet](indexer, kynomeshv1alpha1.Resource("agentset"))}
}

// AgentSets returns an object that can list and get AgentSets.
func (s *agentSetLister) AgentSets(namespace string) AgentSetNamespaceLister {
	return agentSetNamespaceLister{listers.NewNamespaced[*kynomeshv1alpha1.AgentSet](s.ResourceIndexer, namespace)}
}

// AgentSetNamespaceLister helps list and get AgentSets.
// All objects returned here must be treated as read-only.
type AgentSetNamespaceLister interface {
	// List lists all AgentSets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kynomeshv1alpha1.AgentSet, err error)
	// Get retrieves the AgentSet from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kynomeshv1alpha1.AgentSet, error)
	AgentSetNamespaceListerExpansion
}

// agentSetNamespaceLister implements the AgentSetNamespaceLister
// interface.
type agentSetNamespaceLister struct {
	listers.ResourceIndexer[*kynomeshv1alpha1.AgentSet]
}
