/*
Copyright 2026 The Kynoproj Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	kynomeshv1alpha1 "github.com/kynoproj/kynomesh/pkg/apis/kynomesh/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AgentDeployLister helps list AgentDeploys.
// All objects returned here must be treated as read-only.
type AgentDeployLister interface {
	// List lists all AgentDeploys in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kynomeshv1alpha1.AgentDeploy, err error)
	// AgentDeploys returns an object that can list and get AgentDeploys.
	AgentDeploys(namespace string) AgentDeployNamespaceLister
	AgentDeployListerExpansion
}

// agentDeployLister implements the AgentDeployLister interface.
type agentDeployLister struct {
	listers.ResourceIndexer[*kynomeshv1alpha1.AgentDeploy]
}

// NewAgentDeployLister returns a new AgentDeployLister.
func NewAgentDeployLister(indexer cache.Indexer) AgentDeployLister {
	return &agentDeployLister{listers.New[*kynomeshv1alpha1.AgentDeploy](indexer, kynomeshv1alpha1.Resource("agentdeploy"))}
}

// AgentDeploys returns an object that can list and get AgentDeploys.
func (s *agentDeployLister) AgentDeploys(namespace string) AgentDeployNamespaceLister {
	return agentDeployNamespaceLister{listers.NewNamespaced[*kynomeshv1alpha1.AgentDeploy](s.ResourceIndexer, namespace)}
}

// AgentDeployNamespaceLister helps list and get AgentDeploys.
// All objects returned here must be treated as read-only.
type AgentDeployNamespaceLister interface {
	// List lists all AgentDeploys in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kynomeshv1alpha1.AgentDeploy, err error)
	// Get retrieves the AgentDeploy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kynomeshv1alpha1.AgentDeploy, error)
	AgentDeployNamespaceListerExpansion
}

// agentDeployNamespaceLister implements the AgentDeployNamespaceLister
// interface.
type agentDeployNamespaceLister struct {
	listers.ResourceIndexer[*kynomeshv1alpha1.AgentDeploy]
}
