apiVersion: v1
kind: ConfigMap
metadata:
  name: kynomesh-controller-config
data:
  controller-config.yaml: |+
    # "instance" configuration can be used to run multiple controllers
    instance: ""
    defaults:
      containerResources: |
        requests:
          memory: "128Mi"
          cpu: "100m"
