//
//Copyright 2026 The Kynoproj Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v5.27.2
// source: pkg/apis/proto/daemon/daemon.proto

package daemon

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransportWindowedMetrics carries per-window aggregations for a single
// transport bucket (e.g. "jsonrpc", "rest", "grpc", "passthrough").
//
// Keys for the inner maps are window labels: "1m", "5m", "15m" are
// always populated when sufficient samples exist; "custom" is populated
// only when the caller requests a non-zero lookback_seconds.
//
// processingRates values are requests-per-second over the window: one
// HTTP request completion or one gRPC stream close counts as one.
//
// streamMessageRates values are stream-messages-per-second over the
// window: one SSE event (REST/passthrough) or one server→client gRPC
// frame counts as one. Stays at zero for unary responses.
//
// inflights values are time-weighted average in-flight requests over
// the window.
//
// Absent keys in any map mean "no data available for this window."
// Callers must check presence before reading a value.
type TransportWindowedMetrics struct {
	state              protoimpl.MessageState             `protogen:"open.v1"`
	ProcessingRates    map[string]*wrapperspb.DoubleValue `protobuf:"bytes,1,rep,name=processingRates,proto3" json:"processingRates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Inflights          map[string]*wrapperspb.DoubleValue `protobuf:"bytes,2,rep,name=inflights,proto3" json:"inflights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StreamMessageRates map[string]*wrapperspb.DoubleValue `protobuf:"bytes,3,rep,name=streamMessageRates,proto3" json:"streamMessageRates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TransportWindowedMetrics) Reset() {
	*x = TransportWindowedMetrics{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportWindowedMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportWindowedMetrics) ProtoMessage() {}

func (x *TransportWindowedMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportWindowedMetrics.ProtoReflect.Descriptor instead.
func (*TransportWindowedMetrics) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *TransportWindowedMetrics) GetProcessingRates() map[string]*wrapperspb.DoubleValue {
	if x != nil {
		return x.ProcessingRates
	}
	return nil
}

func (x *TransportWindowedMetrics) GetInflights() map[string]*wrapperspb.DoubleValue {
	if x != nil {
		return x.Inflights
	}
	return nil
}

func (x *TransportWindowedMetrics) GetStreamMessageRates() map[string]*wrapperspb.DoubleValue {
	if x != nil {
		return x.StreamMessageRates
	}
	return nil
}

// AgentDeployMetrics carries the aggregated, time-windowed metrics for a
// single AgentDeploy that this daemon scrapes.
//
// Top-level processingRates, streamMessageRates, and inflights are the
// totals across all transports — the common case for autoscaling.
// byTransport carries the per-transport breakdown for callers that need
// finer-grained signal.
type AgentDeployMetrics struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Agentdeploy string                 `protobuf:"bytes,1,opt,name=agentdeploy,proto3" json:"agentdeploy,omitempty"`
	// Totals across all transports. Keys: "1m", "5m", "15m", "custom".
	// See TransportWindowedMetrics for the per-key value semantics.
	ProcessingRates    map[string]*wrapperspb.DoubleValue `protobuf:"bytes,2,rep,name=processingRates,proto3" json:"processingRates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StreamMessageRates map[string]*wrapperspb.DoubleValue `protobuf:"bytes,3,rep,name=streamMessageRates,proto3" json:"streamMessageRates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Inflights          map[string]*wrapperspb.DoubleValue `protobuf:"bytes,4,rep,name=inflights,proto3" json:"inflights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Per-transport breakdown. Keys are the transport label values emitted
	// by the broker (e.g. "jsonrpc", "rest", "grpc", "passthrough"). The
	// daemon is label-agnostic and exposes whatever values it observes.
	ByTransport map[string]*TransportWindowedMetrics `protobuf:"bytes,5,rep,name=byTransport,proto3" json:"byTransport,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The actual window used for the "custom" key, after clamping to the
	// daemon's retention. Unset when the caller did not request a custom
	// lookback.
	CustomWindowEffectiveSeconds *wrapperspb.Int64Value `protobuf:"bytes,6,opt,name=custom_window_effective_seconds,json=customWindowEffectiveSeconds,proto3" json:"custom_window_effective_seconds,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *AgentDeployMetrics) Reset() {
	*x = AgentDeployMetrics{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDeployMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDeployMetrics) ProtoMessage() {}

func (x *AgentDeployMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDeployMetrics.ProtoReflect.Descriptor instead.
func (*AgentDeployMetrics) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *AgentDeployMetrics) GetAgentdeploy() string {
	if x != nil {
		return x.Agentdeploy
	}
	return ""
}

func (x *AgentDeployMetrics) GetProcessingRates() map[string]*wrapperspb.DoubleValue {
	if x != nil {
		return x.ProcessingRates
	}
	return nil
}

func (x *AgentDeployMetrics) GetStreamMessageRates() map[string]*wrapperspb.DoubleValue {
	if x != nil {
		return x.StreamMessageRates
	}
	return nil
}

func (x *AgentDeployMetrics) GetInflights() map[string]*wrapperspb.DoubleValue {
	if x != nil {
		return x.Inflights
	}
	return nil
}

func (x *AgentDeployMetrics) GetByTransport() map[string]*TransportWindowedMetrics {
	if x != nil {
		return x.ByTransport
	}
	return nil
}

func (x *AgentDeployMetrics) GetCustomWindowEffectiveSeconds() *wrapperspb.Int64Value {
	if x != nil {
		return x.CustomWindowEffectiveSeconds
	}
	return nil
}

type GetAgentDeployMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AgentDeploy name. Must be one of the AgentDeploys this daemon is
	// configured to track. Returns NotFound otherwise.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional caller-supplied lookback in seconds. When > 0, the daemon
	// computes an additional "custom" window. Values above the daemon's
	// retention are clamped silently; the actual window used is echoed
	// back in custom_window_effective_seconds.
	LookbackSeconds int64 `protobuf:"varint,2,opt,name=lookback_seconds,json=lookbackSeconds,proto3" json:"lookback_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAgentDeployMetricsRequest) Reset() {
	*x = GetAgentDeployMetricsRequest{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentDeployMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentDeployMetricsRequest) ProtoMessage() {}

func (x *GetAgentDeployMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentDeployMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetAgentDeployMetricsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *GetAgentDeployMetricsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAgentDeployMetricsRequest) GetLookbackSeconds() int64 {
	if x != nil {
		return x.LookbackSeconds
	}
	return 0
}

type GetAgentDeployMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *AgentDeployMetrics    `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentDeployMetricsResponse) Reset() {
	*x = GetAgentDeployMetricsResponse{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentDeployMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentDeployMetricsResponse) ProtoMessage() {}

func (x *GetAgentDeployMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentDeployMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetAgentDeployMetricsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *GetAgentDeployMetricsResponse) GetMetrics() *AgentDeployMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_pkg_apis_proto_daemon_daemon_proto protoreflect.FileDescriptor

const file_pkg_apis_proto_daemon_daemon_proto_rawDesc = "" +
	"\n" +
	"\"pkg/apis/proto/daemon/daemon.proto\x12\x12kynomesh.daemon.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xfb\x04\n" +
	"\x18TransportWindowedMetrics\x12k\n" +
	"\x0fprocessingRates\x18\x01 \x03(\v2A.kynomesh.daemon.v1.TransportWindowedMetrics.ProcessingRatesEntryR\x0fprocessingRates\x12Y\n" +
	"\tinflights\x18\x02 \x03(\v2;.kynomesh.daemon.v1.TransportWindowedMetrics.InflightsEntryR\tinflights\x12t\n" +
	"\x12streamMessageRates\x18\x03 \x03(\v2D.kynomesh.daemon.v1.TransportWindowedMetrics.StreamMessageRatesEntryR\x12streamMessageRates\x1a`\n" +
	"\x14ProcessingRatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05value:\x028\x01\x1aZ\n" +
	"\x0eInflightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05value:\x028\x01\x1ac\n" +
	"\x17StreamMessageRatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05value:\x028\x01\"\xb2\a\n" +
	"\x12AgentDeployMetrics\x12 \n" +
	"\vagentdeploy\x18\x01 \x01(\tR\vagentdeploy\x12e\n" +
	"\x0fprocessingRates\x18\x02 \x03(\v2;.kynomesh.daemon.v1.AgentDeployMetrics.ProcessingRatesEntryR\x0fprocessingRates\x12n\n" +
	"\x12streamMessageRates\x18\x03 \x03(\v2>.kynomesh.daemon.v1.AgentDeployMetrics.StreamMessageRatesEntryR\x12streamMessageRates\x12S\n" +
	"\tinflights\x18\x04 \x03(\v25.kynomesh.daemon.v1.AgentDeployMetrics.InflightsEntryR\tinflights\x12Y\n" +
	"\vbyTransport\x18\x05 \x03(\v27.kynomesh.daemon.v1.AgentDeployMetrics.ByTransportEntryR\vbyTransport\x12b\n" +
	"\x1fcustom_window_effective_seconds\x18\x06 \x01(\v2\x1b.google.protobuf.Int64ValueR\x1ccustomWindowEffectiveSeconds\x1a`\n" +
	"\x14ProcessingRatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05value:\x028\x01\x1ac\n" +
	"\x17StreamMessageRatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05value:\x028\x01\x1aZ\n" +
	"\x0eInflightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05value:\x028\x01\x1al\n" +
	"\x10ByTransportEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12B\n" +
	"\x05value\x18\x02 \x01(\v2,.kynomesh.daemon.v1.TransportWindowedMetricsR\x05value:\x028\x01\"]\n" +
	"\x1cGetAgentDeployMetricsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x10lookback_seconds\x18\x02 \x01(\x03R\x0flookbackSeconds\"a\n" +
	"\x1dGetAgentDeployMetricsResponse\x12@\n" +
	"\ametrics\x18\x01 \x01(\v2&.kynomesh.daemon.v1.AgentDeployMetricsR\ametrics2\xbb\x01\n" +
	"\rDaemonService\x12\xa9\x01\n" +
	"\x15GetAgentDeployMetrics\x120.kynomesh.daemon.v1.GetAgentDeployMetricsRequest\x1a1.kynomesh.daemon.v1.GetAgentDeployMetricsResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1/agentdeploys/{name}/metricsB4Z2github.com/kynoproj/kynomesh/pkg/apis/proto/daemonb\x06proto3"

var (
	file_pkg_apis_proto_daemon_daemon_proto_rawDescOnce sync.Once
	file_pkg_apis_proto_daemon_daemon_proto_rawDescData []byte
)

func file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP() []byte {
	file_pkg_apis_proto_daemon_daemon_proto_rawDescOnce.Do(func() {
		file_pkg_apis_proto_daemon_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_apis_proto_daemon_daemon_proto_rawDesc), len(file_pkg_apis_proto_daemon_daemon_proto_rawDesc)))
	})
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescData
}

var file_pkg_apis_proto_daemon_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_apis_proto_daemon_daemon_proto_goTypes = []any{
	(*TransportWindowedMetrics)(nil),      // 0: kynomesh.daemon.v1.TransportWindowedMetrics
	(*AgentDeployMetrics)(nil),            // 1: kynomesh.daemon.v1.AgentDeployMetrics
	(*GetAgentDeployMetricsRequest)(nil),  // 2: kynomesh.daemon.v1.GetAgentDeployMetricsRequest
	(*GetAgentDeployMetricsResponse)(nil), // 3: kynomesh.daemon.v1.GetAgentDeployMetricsResponse
	nil,                                   // 4: kynomesh.daemon.v1.TransportWindowedMetrics.ProcessingRatesEntry
	nil,                                   // 5: kynomesh.daemon.v1.TransportWindowedMetrics.InflightsEntry
	nil,                                   // 6: kynomesh.daemon.v1.TransportWindowedMetrics.StreamMessageRatesEntry
	nil,                                   // 7: kynomesh.daemon.v1.AgentDeployMetrics.ProcessingRatesEntry
	nil,                                   // 8: kynomesh.daemon.v1.AgentDeployMetrics.StreamMessageRatesEntry
	nil,                                   // 9: kynomesh.daemon.v1.AgentDeployMetrics.InflightsEntry
	nil,                                   // 10: kynomesh.daemon.v1.AgentDeployMetrics.ByTransportEntry
	(*wrapperspb.Int64Value)(nil),         // 11: google.protobuf.Int64Value
	(*wrapperspb.DoubleValue)(nil),        // 12: google.protobuf.DoubleValue
}
var file_pkg_apis_proto_daemon_daemon_proto_depIdxs = []int32{
	4,  // 0: kynomesh.daemon.v1.TransportWindowedMetrics.processingRates:type_name -> kynomesh.daemon.v1.TransportWindowedMetrics.ProcessingRatesEntry
	5,  // 1: kynomesh.daemon.v1.TransportWindowedMetrics.inflights:type_name -> kynomesh.daemon.v1.TransportWindowedMetrics.InflightsEntry
	6,  // 2: kynomesh.daemon.v1.TransportWindowedMetrics.streamMessageRates:type_name -> kynomesh.daemon.v1.TransportWindowedMetrics.StreamMessageRatesEntry
	7,  // 3: kynomesh.daemon.v1.AgentDeployMetrics.processingRates:type_name -> kynomesh.daemon.v1.AgentDeployMetrics.ProcessingRatesEntry
	8,  // 4: kynomesh.daemon.v1.AgentDeployMetrics.streamMessageRates:type_name -> kynomesh.daemon.v1.AgentDeployMetrics.StreamMessageRatesEntry
	9,  // 5: kynomesh.daemon.v1.AgentDeployMetrics.inflights:type_name -> kynomesh.daemon.v1.AgentDeployMetrics.InflightsEntry
	10, // 6: kynomesh.daemon.v1.AgentDeployMetrics.byTransport:type_name -> kynomesh.daemon.v1.AgentDeployMetrics.ByTransportEntry
	11, // 7: kynomesh.daemon.v1.AgentDeployMetrics.custom_window_effective_seconds:type_name -> google.protobuf.Int64Value
	1,  // 8: kynomesh.daemon.v1.GetAgentDeployMetricsResponse.metrics:type_name -> kynomesh.daemon.v1.AgentDeployMetrics
	12, // 9: kynomesh.daemon.v1.TransportWindowedMetrics.ProcessingRatesEntry.value:type_name -> google.protobuf.DoubleValue
	12, // 10: kynomesh.daemon.v1.TransportWindowedMetrics.InflightsEntry.value:type_name -> google.protobuf.DoubleValue
	12, // 11: kynomesh.daemon.v1.TransportWindowedMetrics.StreamMessageRatesEntry.value:type_name -> google.protobuf.DoubleValue
	12, // 12: kynomesh.daemon.v1.AgentDeployMetrics.ProcessingRatesEntry.value:type_name -> google.protobuf.DoubleValue
	12, // 13: kynomesh.daemon.v1.AgentDeployMetrics.StreamMessageRatesEntry.value:type_name -> google.protobuf.DoubleValue
	12, // 14: kynomesh.daemon.v1.AgentDeployMetrics.InflightsEntry.value:type_name -> google.protobuf.DoubleValue
	0,  // 15: kynomesh.daemon.v1.AgentDeployMetrics.ByTransportEntry.value:type_name -> kynomesh.daemon.v1.TransportWindowedMetrics
	2,  // 16: kynomesh.daemon.v1.DaemonService.GetAgentDeployMetrics:input_type -> kynomesh.daemon.v1.GetAgentDeployMetricsRequest
	3,  // 17: kynomesh.daemon.v1.DaemonService.GetAgentDeployMetrics:output_type -> kynomesh.daemon.v1.GetAgentDeployMetricsResponse
	17, // [17:18] is the sub-list for method output_type
	16, // [16:17] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_pkg_apis_proto_daemon_daemon_proto_init() }
func file_pkg_apis_proto_daemon_daemon_proto_init() {
	if File_pkg_apis_proto_daemon_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_apis_proto_daemon_daemon_proto_rawDesc), len(file_pkg_apis_proto_daemon_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_apis_proto_daemon_daemon_proto_goTypes,
		DependencyIndexes: file_pkg_apis_proto_daemon_daemon_proto_depIdxs,
		MessageInfos:      file_pkg_apis_proto_daemon_daemon_proto_msgTypes,
	}.Build()
	File_pkg_apis_proto_daemon_daemon_proto = out.File
	file_pkg_apis_proto_daemon_daemon_proto_goTypes = nil
	file_pkg_apis_proto_daemon_daemon_proto_depIdxs = nil
}
