//
//Copyright 2026 The Kynoproj Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.27.2
// source: pkg/apis/proto/daemon/daemon.proto

package daemon

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransportWindowedMetrics carries per-window aggregations for a single
// transport bucket (e.g. "jsonrpc", "rest", "grpc", "passthrough").
//
// Keys for the inner maps are window labels: "1m", "5m", "15m" are
// always populated when sufficient samples exist; "custom" is populated
// only when the caller requests a non-zero lookback_seconds.
//
// processingRates values are requests-per-second over the window: one
// HTTP request completion or one gRPC stream close counts as one.
//
// streamMessageRates values are stream-messages-per-second over the
// window: one SSE event (REST/passthrough) or one server→client gRPC
// frame counts as one. Stays at zero for unary responses.
//
// inflights values are time-weighted average in-flight requests over
// the window.
//
// Absent keys in any map mean "no data available for this window."
// Callers must check presence before reading a value.
type TransportWindowedMetrics struct {
	state              protoimpl.MessageState             `protogen:"open.v1"`
	ProcessingRates    map[string]*wrapperspb.DoubleValue `protobuf:"bytes,1,rep,name=processingRates,proto3" json:"processingRates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Inflights          map[string]*wrapperspb.DoubleValue `protobuf:"bytes,2,rep,name=inflights,proto3" json:"inflights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StreamMessageRates map[string]*wrapperspb.DoubleValue `protobuf:"bytes,3,rep,name=streamMessageRates,proto3" json:"streamMessageRates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TransportWindowedMetrics) Reset() {
	*x = TransportWindowedMetrics{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportWindowedMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportWindowedMetrics) ProtoMessage() {}

func (x *TransportWindowedMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportWindowedMetrics.ProtoReflect.Descriptor instead.
func (*TransportWindowedMetrics) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *TransportWindowedMetrics) GetProcessingRates() map[string]*wrapperspb.DoubleValue {
	if x != nil {
		return x.ProcessingRates
	}
	return nil
}

func (x *TransportWindowedMetrics) GetInflights() map[string]*wrapperspb.DoubleValue {
	if x != nil {
		return x.Inflights
	}
	return nil
}

func (x *TransportWindowedMetrics) GetStreamMessageRates() map[string]*wrapperspb.DoubleValue {
	if x != nil {
		return x.StreamMessageRates
	}
	return nil
}

// AgentDeployMetrics carries the aggregated, time-windowed metrics for a
// single AgentDeploy that this daemon scrapes.
type AgentDeployMetrics struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AgentSet    string                 `protobuf:"bytes,1,opt,name=agentSet,proto3" json:"agentSet,omitempty"`
	AgentDeploy string                 `protobuf:"bytes,2,opt,name=agentDeploy,proto3" json:"agentDeploy,omitempty"`
	// Totals across all transports. Keys: "1m", "5m", "15m", "custom".
	// See TransportWindowedMetrics for the per-key value semantics.
	ProcessingRates    map[string]*wrapperspb.DoubleValue `protobuf:"bytes,3,rep,name=processingRates,proto3" json:"processingRates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StreamMessageRates map[string]*wrapperspb.DoubleValue `protobuf:"bytes,4,rep,name=streamMessageRates,proto3" json:"streamMessageRates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Inflights          map[string]*wrapperspb.DoubleValue `protobuf:"bytes,5,rep,name=inflights,proto3" json:"inflights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Per-transport breakdown. Keys are the transport label values emitted
	// by the broker (e.g. "jsonrpc", "rest", "grpc", "passthrough"). The
	// daemon is label-agnostic and exposes whatever values it observes.
	ByTransport map[string]*TransportWindowedMetrics `protobuf:"bytes,6,rep,name=byTransport,proto3" json:"byTransport,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The actual window used for the "custom" key, after clamping to the
	// daemon's retention. Unset when the caller did not request a custom
	// lookback.
	CustomWindowEffectiveSeconds *wrapperspb.Int64Value `protobuf:"bytes,7,opt,name=customWindowEffectiveSeconds,proto3" json:"customWindowEffectiveSeconds,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *AgentDeployMetrics) Reset() {
	*x = AgentDeployMetrics{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDeployMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDeployMetrics) ProtoMessage() {}

func (x *AgentDeployMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDeployMetrics.ProtoReflect.Descriptor instead.
func (*AgentDeployMetrics) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *AgentDeployMetrics) GetAgentSet() string {
	if x != nil {
		return x.AgentSet
	}
	return ""
}

func (x *AgentDeployMetrics) GetAgentDeploy() string {
	if x != nil {
		return x.AgentDeploy
	}
	return ""
}

func (x *AgentDeployMetrics) GetProcessingRates() map[string]*wrapperspb.DoubleValue {
	if x != nil {
		return x.ProcessingRates
	}
	return nil
}

func (x *AgentDeployMetrics) GetStreamMessageRates() map[string]*wrapperspb.DoubleValue {
	if x != nil {
		return x.StreamMessageRates
	}
	return nil
}

func (x *AgentDeployMetrics) GetInflights() map[string]*wrapperspb.DoubleValue {
	if x != nil {
		return x.Inflights
	}
	return nil
}

func (x *AgentDeployMetrics) GetByTransport() map[string]*TransportWindowedMetrics {
	if x != nil {
		return x.ByTransport
	}
	return nil
}

func (x *AgentDeployMetrics) GetCustomWindowEffectiveSeconds() *wrapperspb.Int64Value {
	if x != nil {
		return x.CustomWindowEffectiveSeconds
	}
	return nil
}

type GetAgentDeployMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AgentDeploy name. Must be one of the AgentDeploys this daemon is
	// configured to track. Returns NotFound otherwise.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional caller-supplied lookback in seconds. When > 0, the daemon
	// computes an additional "custom" window. Values above the daemon's
	// retention are clamped silently; the actual window used is echoed
	// back in customWindowEffectiveSeconds.
	LookbackSeconds int64 `protobuf:"varint,2,opt,name=lookbackSeconds,proto3" json:"lookbackSeconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAgentDeployMetricsRequest) Reset() {
	*x = GetAgentDeployMetricsRequest{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentDeployMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentDeployMetricsRequest) ProtoMessage() {}

func (x *GetAgentDeployMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentDeployMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetAgentDeployMetricsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *GetAgentDeployMetricsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAgentDeployMetricsRequest) GetLookbackSeconds() int64 {
	if x != nil {
		return x.LookbackSeconds
	}
	return 0
}

type GetAgentDeployMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *AgentDeployMetrics    `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentDeployMetricsResponse) Reset() {
	*x = GetAgentDeployMetricsResponse{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentDeployMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentDeployMetricsResponse) ProtoMessage() {}

func (x *GetAgentDeployMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentDeployMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetAgentDeployMetricsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *GetAgentDeployMetricsResponse) GetMetrics() *AgentDeployMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// PeerCardDrift carries one peer's drift-comparison state for a single
// dependent AgentDeploy.
type PeerCardDrift struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// latestHash is the daemon's own polled, stability-gated AgentCard hash
	// for this peer. Empty when the daemon has not yet completed a stable
	// poll for this peer.
	LatestHash string `protobuf:"bytes,1,opt,name=latestHash,proto3" json:"latestHash,omitempty"`
	// latestHashObservedAt is when the daemon's stability gate last accepted
	// latestHash.
	LatestHashObservedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=latestHashObservedAt,proto3" json:"latestHashObservedAt,omitempty"`
	// reportedHashes is keyed by pod name, holding what that pod currently
	// reports for this peer (via its broker-exposed peer-hashes endpoint).
	// A pod with no entry has not reported a hash for this peer yet —
	// "unknown," not "drifted."
	ReportedHashes map[string]*ReportedHash `protobuf:"bytes,2,rep,name=reportedHashes,proto3" json:"reportedHashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PeerCardDrift) Reset() {
	*x = PeerCardDrift{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerCardDrift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerCardDrift) ProtoMessage() {}

func (x *PeerCardDrift) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerCardDrift.ProtoReflect.Descriptor instead.
func (*PeerCardDrift) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *PeerCardDrift) GetLatestHash() string {
	if x != nil {
		return x.LatestHash
	}
	return ""
}

func (x *PeerCardDrift) GetLatestHashObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LatestHashObservedAt
	}
	return nil
}

func (x *PeerCardDrift) GetReportedHashes() map[string]*ReportedHash {
	if x != nil {
		return x.ReportedHashes
	}
	return nil
}

// ReportedHash is a single pod's self-reported AgentCard hash for one peer.
type ReportedHash struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hash is that pod's currently-reported AgentCard hash for this peer.
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// observedAt is when that pod's agent SDK recorded this hash.
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=observedAt,proto3" json:"observedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportedHash) Reset() {
	*x = ReportedHash{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportedHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportedHash) ProtoMessage() {}

func (x *ReportedHash) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportedHash.ProtoReflect.Descriptor instead.
func (*ReportedHash) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *ReportedHash) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ReportedHash) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

type GetPeerCardDriftRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AgentDeploy name. Must be one of the AgentDeploys this daemon is
	// configured to track. Returns NotFound otherwise.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeerCardDriftRequest) Reset() {
	*x = GetPeerCardDriftRequest{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerCardDriftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerCardDriftRequest) ProtoMessage() {}

func (x *GetPeerCardDriftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerCardDriftRequest.ProtoReflect.Descriptor instead.
func (*GetPeerCardDriftRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *GetPeerCardDriftRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPeerCardDriftResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Keyed by peer name (as it appears in the AgentDeploy's topology).
	Peers         map[string]*PeerCardDrift `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeerCardDriftResponse) Reset() {
	*x = GetPeerCardDriftResponse{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerCardDriftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerCardDriftResponse) ProtoMessage() {}

func (x *GetPeerCardDriftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerCardDriftResponse.ProtoReflect.Descriptor instead.
func (*GetPeerCardDriftResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *GetPeerCardDriftResponse) GetPeers() map[string]*PeerCardDrift {
	if x != nil {
		return x.Peers
	}
	return nil
}

var File_pkg_apis_proto_daemon_daemon_proto protoreflect.FileDescriptor

const file_pkg_apis_proto_daemon_daemon_proto_rawDesc = "" +
	"\n" +
	"\"pkg/apis/proto/daemon/daemon.proto\x12\x12kynomesh.daemon.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xfb\x04\n" +
	"\x18TransportWindowedMetrics\x12k\n" +
	"\x0fprocessingRates\x18\x01 \x03(\v2A.kynomesh.daemon.v1.TransportWindowedMetrics.ProcessingRatesEntryR\x0fprocessingRates\x12Y\n" +
	"\tinflights\x18\x02 \x03(\v2;.kynomesh.daemon.v1.TransportWindowedMetrics.InflightsEntryR\tinflights\x12t\n" +
	"\x12streamMessageRates\x18\x03 \x03(\v2D.kynomesh.daemon.v1.TransportWindowedMetrics.StreamMessageRatesEntryR\x12streamMessageRates\x1a`\n" +
	"\x14ProcessingRatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05value:\x028\x01\x1aZ\n" +
	"\x0eInflightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05value:\x028\x01\x1ac\n" +
	"\x17StreamMessageRatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05value:\x028\x01\"\xcb\a\n" +
	"\x12AgentDeployMetrics\x12\x1a\n" +
	"\bagentSet\x18\x01 \x01(\tR\bagentSet\x12 \n" +
	"\vagentDeploy\x18\x02 \x01(\tR\vagentDeploy\x12e\n" +
	"\x0fprocessingRates\x18\x03 \x03(\v2;.kynomesh.daemon.v1.AgentDeployMetrics.ProcessingRatesEntryR\x0fprocessingRates\x12n\n" +
	"\x12streamMessageRates\x18\x04 \x03(\v2>.kynomesh.daemon.v1.AgentDeployMetrics.StreamMessageRatesEntryR\x12streamMessageRates\x12S\n" +
	"\tinflights\x18\x05 \x03(\v25.kynomesh.daemon.v1.AgentDeployMetrics.InflightsEntryR\tinflights\x12Y\n" +
	"\vbyTransport\x18\x06 \x03(\v27.kynomesh.daemon.v1.AgentDeployMetrics.ByTransportEntryR\vbyTransport\x12_\n" +
	"\x1ccustomWindowEffectiveSeconds\x18\a \x01(\v2\x1b.google.protobuf.Int64ValueR\x1ccustomWindowEffectiveSeconds\x1a`\n" +
	"\x14ProcessingRatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05value:\x028\x01\x1ac\n" +
	"\x17StreamMessageRatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05value:\x028\x01\x1aZ\n" +
	"\x0eInflightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05value:\x028\x01\x1al\n" +
	"\x10ByTransportEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12B\n" +
	"\x05value\x18\x02 \x01(\v2,.kynomesh.daemon.v1.TransportWindowedMetricsR\x05value:\x028\x01\"\\\n" +
	"\x1cGetAgentDeployMetricsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x0flookbackSeconds\x18\x02 \x01(\x03R\x0flookbackSeconds\"a\n" +
	"\x1dGetAgentDeployMetricsResponse\x12@\n" +
	"\ametrics\x18\x01 \x01(\v2&.kynomesh.daemon.v1.AgentDeployMetricsR\ametrics\"\xc3\x02\n" +
	"\rPeerCardDrift\x12\x1e\n" +
	"\n" +
	"latestHash\x18\x01 \x01(\tR\n" +
	"latestHash\x12N\n" +
	"\x14latestHashObservedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x14latestHashObservedAt\x12]\n" +
	"\x0ereportedHashes\x18\x02 \x03(\v25.kynomesh.daemon.v1.PeerCardDrift.ReportedHashesEntryR\x0ereportedHashes\x1ac\n" +
	"\x13ReportedHashesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .kynomesh.daemon.v1.ReportedHashR\x05value:\x028\x01\"^\n" +
	"\fReportedHash\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12:\n" +
	"\n" +
	"observedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\"-\n" +
	"\x17GetPeerCardDriftRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xc6\x01\n" +
	"\x18GetPeerCardDriftResponse\x12M\n" +
	"\x05peers\x18\x01 \x03(\v27.kynomesh.daemon.v1.GetPeerCardDriftResponse.PeersEntryR\x05peers\x1a[\n" +
	"\n" +
	"PeersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.kynomesh.daemon.v1.PeerCardDriftR\x05value:\x028\x012\xe0\x02\n" +
	"\rDaemonService\x12\xa9\x01\n" +
	"\x15GetAgentDeployMetrics\x120.kynomesh.daemon.v1.GetAgentDeployMetricsRequest\x1a1.kynomesh.daemon.v1.GetAgentDeployMetricsResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1/agentdeploys/{name}/metrics\x12\xa2\x01\n" +
	"\x10GetPeerCardDrift\x12+.kynomesh.daemon.v1.GetPeerCardDriftRequest\x1a,.kynomesh.daemon.v1.GetPeerCardDriftResponse\"3\x82\xd3\xe4\x93\x02-\x12+/api/v1/agentdeploys/{name}/peer-card-driftB4Z2github.com/kynoproj/kynomesh/pkg/apis/proto/daemonb\x06proto3"

var (
	file_pkg_apis_proto_daemon_daemon_proto_rawDescOnce sync.Once
	file_pkg_apis_proto_daemon_daemon_proto_rawDescData []byte
)

func file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP() []byte {
	file_pkg_apis_proto_daemon_daemon_proto_rawDescOnce.Do(func() {
		file_pkg_apis_proto_daemon_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_apis_proto_daemon_daemon_proto_rawDesc), len(file_pkg_apis_proto_daemon_daemon_proto_rawDesc)))
	})
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescData
}

var file_pkg_apis_proto_daemon_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pkg_apis_proto_daemon_daemon_proto_goTypes = []any{
	(*TransportWindowedMetrics)(nil),      // 0: kynomesh.daemon.v1.TransportWindowedMetrics
	(*AgentDeployMetrics)(nil),            // 1: kynomesh.daemon.v1.AgentDeployMetrics
	(*GetAgentDeployMetricsRequest)(nil),  // 2: kynomesh.daemon.v1.GetAgentDeployMetricsRequest
	(*GetAgentDeployMetricsResponse)(nil), // 3: kynomesh.daemon.v1.GetAgentDeployMetricsResponse
	(*PeerCardDrift)(nil),                 // 4: kynomesh.daemon.v1.PeerCardDrift
	(*ReportedHash)(nil),                  // 5: kynomesh.daemon.v1.ReportedHash
	(*GetPeerCardDriftRequest)(nil),       // 6: kynomesh.daemon.v1.GetPeerCardDriftRequest
	(*GetPeerCardDriftResponse)(nil),      // 7: kynomesh.daemon.v1.GetPeerCardDriftResponse
	nil,                                   // 8: kynomesh.daemon.v1.TransportWindowedMetrics.ProcessingRatesEntry
	nil,                                   // 9: kynomesh.daemon.v1.TransportWindowedMetrics.InflightsEntry
	nil,                                   // 10: kynomesh.daemon.v1.TransportWindowedMetrics.StreamMessageRatesEntry
	nil,                                   // 11: kynomesh.daemon.v1.AgentDeployMetrics.ProcessingRatesEntry
	nil,                                   // 12: kynomesh.daemon.v1.AgentDeployMetrics.StreamMessageRatesEntry
	nil,                                   // 13: kynomesh.daemon.v1.AgentDeployMetrics.InflightsEntry
	nil,                                   // 14: kynomesh.daemon.v1.AgentDeployMetrics.ByTransportEntry
	nil,                                   // 15: kynomesh.daemon.v1.PeerCardDrift.ReportedHashesEntry
	nil,                                   // 16: kynomesh.daemon.v1.GetPeerCardDriftResponse.PeersEntry
	(*wrapperspb.Int64Value)(nil),         // 17: google.protobuf.Int64Value
	(*timestamppb.Timestamp)(nil),         // 18: google.protobuf.Timestamp
	(*wrapperspb.DoubleValue)(nil),        // 19: google.protobuf.DoubleValue
}
var file_pkg_apis_proto_daemon_daemon_proto_depIdxs = []int32{
	8,  // 0: kynomesh.daemon.v1.TransportWindowedMetrics.processingRates:type_name -> kynomesh.daemon.v1.TransportWindowedMetrics.ProcessingRatesEntry
	9,  // 1: kynomesh.daemon.v1.TransportWindowedMetrics.inflights:type_name -> kynomesh.daemon.v1.TransportWindowedMetrics.InflightsEntry
	10, // 2: kynomesh.daemon.v1.TransportWindowedMetrics.streamMessageRates:type_name -> kynomesh.daemon.v1.TransportWindowedMetrics.StreamMessageRatesEntry
	11, // 3: kynomesh.daemon.v1.AgentDeployMetrics.processingRates:type_name -> kynomesh.daemon.v1.AgentDeployMetrics.ProcessingRatesEntry
	12, // 4: kynomesh.daemon.v1.AgentDeployMetrics.streamMessageRates:type_name -> kynomesh.daemon.v1.AgentDeployMetrics.StreamMessageRatesEntry
	13, // 5: kynomesh.daemon.v1.AgentDeployMetrics.inflights:type_name -> kynomesh.daemon.v1.AgentDeployMetrics.InflightsEntry
	14, // 6: kynomesh.daemon.v1.AgentDeployMetrics.byTransport:type_name -> kynomesh.daemon.v1.AgentDeployMetrics.ByTransportEntry
	17, // 7: kynomesh.daemon.v1.AgentDeployMetrics.customWindowEffectiveSeconds:type_name -> google.protobuf.Int64Value
	1,  // 8: kynomesh.daemon.v1.GetAgentDeployMetricsResponse.metrics:type_name -> kynomesh.daemon.v1.AgentDeployMetrics
	18, // 9: kynomesh.daemon.v1.PeerCardDrift.latestHashObservedAt:type_name -> google.protobuf.Timestamp
	15, // 10: kynomesh.daemon.v1.PeerCardDrift.reportedHashes:type_name -> kynomesh.daemon.v1.PeerCardDrift.ReportedHashesEntry
	18, // 11: kynomesh.daemon.v1.ReportedHash.observedAt:type_name -> google.protobuf.Timestamp
	16, // 12: kynomesh.daemon.v1.GetPeerCardDriftResponse.peers:type_name -> kynomesh.daemon.v1.GetPeerCardDriftResponse.PeersEntry
	19, // 13: kynomesh.daemon.v1.TransportWindowedMetrics.ProcessingRatesEntry.value:type_name -> google.protobuf.DoubleValue
	19, // 14: kynomesh.daemon.v1.TransportWindowedMetrics.InflightsEntry.value:type_name -> google.protobuf.DoubleValue
	19, // 15: kynomesh.daemon.v1.TransportWindowedMetrics.StreamMessageRatesEntry.value:type_name -> google.protobuf.DoubleValue
	19, // 16: kynomesh.daemon.v1.AgentDeployMetrics.ProcessingRatesEntry.value:type_name -> google.protobuf.DoubleValue
	19, // 17: kynomesh.daemon.v1.AgentDeployMetrics.StreamMessageRatesEntry.value:type_name -> google.protobuf.DoubleValue
	19, // 18: kynomesh.daemon.v1.AgentDeployMetrics.InflightsEntry.value:type_name -> google.protobuf.DoubleValue
	0,  // 19: kynomesh.daemon.v1.AgentDeployMetrics.ByTransportEntry.value:type_name -> kynomesh.daemon.v1.TransportWindowedMetrics
	5,  // 20: kynomesh.daemon.v1.PeerCardDrift.ReportedHashesEntry.value:type_name -> kynomesh.daemon.v1.ReportedHash
	4,  // 21: kynomesh.daemon.v1.GetPeerCardDriftResponse.PeersEntry.value:type_name -> kynomesh.daemon.v1.PeerCardDrift
	2,  // 22: kynomesh.daemon.v1.DaemonService.GetAgentDeployMetrics:input_type -> kynomesh.daemon.v1.GetAgentDeployMetricsRequest
	6,  // 23: kynomesh.daemon.v1.DaemonService.GetPeerCardDrift:input_type -> kynomesh.daemon.v1.GetPeerCardDriftRequest
	3,  // 24: kynomesh.daemon.v1.DaemonService.GetAgentDeployMetrics:output_type -> kynomesh.daemon.v1.GetAgentDeployMetricsResponse
	7,  // 25: kynomesh.daemon.v1.DaemonService.GetPeerCardDrift:output_type -> kynomesh.daemon.v1.GetPeerCardDriftResponse
	24, // [24:26] is the sub-list for method output_type
	22, // [22:24] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_pkg_apis_proto_daemon_daemon_proto_init() }
func file_pkg_apis_proto_daemon_daemon_proto_init() {
	if File_pkg_apis_proto_daemon_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_apis_proto_daemon_daemon_proto_rawDesc), len(file_pkg_apis_proto_daemon_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_apis_proto_daemon_daemon_proto_goTypes,
		DependencyIndexes: file_pkg_apis_proto_daemon_daemon_proto_depIdxs,
		MessageInfos:      file_pkg_apis_proto_daemon_daemon_proto_msgTypes,
	}.Build()
	File_pkg_apis_proto_daemon_daemon_proto = out.File
	file_pkg_apis_proto_daemon_daemon_proto_goTypes = nil
	file_pkg_apis_proto_daemon_daemon_proto_depIdxs = nil
}
