apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kynomesh-cluster-role
  labels:
    app.kubernetes.io/name: kynomesh-controller-manager
    app.kubernetes.io/part-of: kynomesh
    app.kubernetes.io/component: controller-manager
rules:
  - apiGroups:
      - kynomesh.kyno.sh
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    resources:
      - agentsets
      - agentsets/finalizers
      - agentsets/status
      - agentdeploys
      - agentdeploys/finalizers
      - agentdeploys/status
      - agentdeploys/scale
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - services
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
