apiVersion: v1
kind: ServiceAccount
metadata:
  name: kynomesh-webhook-sa
  namespace: kynomesh-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kynomesh-webhook
    app.kubernetes.io/name: kynomesh-webhook
    app.kubernetes.io/part-of: kynomesh
  name: kynomesh-webhook
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - kynomesh.kyno.sh
  resources:
  - agentsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: kynomesh-webhook
    app.kubernetes.io/name: kynomesh-webhook
    app.kubernetes.io/part-of: kynomesh
  name: kynomesh-webhook-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kynomesh-webhook
subjects:
- kind: ServiceAccount
  name: kynomesh-webhook-sa
  namespace: kynomesh-system
---
apiVersion: v1
kind: Service
metadata:
  name: kynomesh-webhook
  namespace: kynomesh-system
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app.kubernetes.io/component: kynomesh-webhook
    app.kubernetes.io/name: kynomesh-webhook
    app.kubernetes.io/part-of: kynomesh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kynomesh-webhook
  namespace: kynomesh-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kynomesh-webhook
      app.kubernetes.io/name: kynomesh-webhook
      app.kubernetes.io/part-of: kynomesh
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kynomesh-webhook
        app.kubernetes.io/name: kynomesh-webhook
        app.kubernetes.io/part-of: kynomesh
    spec:
      containers:
      - args:
        - webhook
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PORT
          value: "443"
        - name: DEPLOYMENT_NAME
          value: kynomesh-webhook
        - name: SERVICE_NAME
          value: kynomesh-webhook
        - name: CLUSTER_ROLE_NAME
          value: kynomesh-webhook
        image: quay.io/kynoproj/kynomesh:latest
        imagePullPolicy: Always
        name: webhook
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 200Mi
      serviceAccountName: kynomesh-webhook-sa
