apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kynomesh-webhook
  labels:
    app.kubernetes.io/name: kynomesh-webhook
    app.kubernetes.io/part-of: kynomesh
    app.kubernetes.io/component: kynomesh-webhook
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups:
      - kynomesh.kyno.sh
    verbs:
      - get
      - list
      - watch
    resources:
      - agentsets
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
    verbs:
      - get
      - list
