/*
Copyright 2026 The Kynoproj Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiskynomeshv1alpha1 "github.com/kynoproj/kynomesh/pkg/apis/kynomesh/v1alpha1"
	versioned "github.com/kynoproj/kynomesh/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kynoproj/kynomesh/pkg/client/informers/externalversions/internalinterfaces"
	kynomeshv1alpha1 "github.com/kynoproj/kynomesh/pkg/client/listers/kynomesh/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AgentDeployInformer provides access to a shared informer and lister for
// AgentDeploys.
type AgentDeployInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() kynomeshv1alpha1.AgentDeployLister
}

type agentDeployInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAgentDeployInformer constructs a new informer for AgentDeploy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAgentDeployInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAgentDeployInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAgentDeployInformer constructs a new informer for AgentDeploy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAgentDeployInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KynomeshV1alpha1().AgentDeploys(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KynomeshV1alpha1().AgentDeploys(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KynomeshV1alpha1().AgentDeploys(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KynomeshV1alpha1().AgentDeploys(namespace).Watch(ctx, options)
			},
		}, client),
		&apiskynomeshv1alpha1.AgentDeploy{},
		resyncPeriod,
		indexers,
	)
}

func (f *agentDeployInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAgentDeployInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *agentDeployInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiskynomeshv1alpha1.AgentDeploy{}, f.defaultInformer)
}

func (f *agentDeployInformer) Lister() kynomeshv1alpha1.AgentDeployLister {
	return kynomeshv1alpha1.NewAgentDeployLister(f.Informer().GetIndexer())
}
