/*
Copyright 2026 The Kynoproj Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiskynomeshv1alpha1 "github.com/kynoproj/kynomesh/pkg/apis/kynomesh/v1alpha1"
	versioned "github.com/kynoproj/kynomesh/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kynoproj/kynomesh/pkg/client/informers/externalversions/internalinterfaces"
	kynomeshv1alpha1 "github.com/kynoproj/kynomesh/pkg/client/listers/kynomesh/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AgentDeployInformer provides access to a shared informer and lister for
// AgentDeploys. Prefer using the type-safe variant (see [TypedAgentDeployInformer]).
type AgentDeployInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() kynomeshv1alpha1.AgentDeployLister
}

// TypedAgentDeployInformer provides access to a shared informer and lister for
// AgentDeploys, including the type-safe TypedInformer variant.
// It is a superset of AgentDeployInformer.
type TypedAgentDeployInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() AgentDeployIndexInformer
	Lister() kynomeshv1alpha1.AgentDeployLister
}

// AgentDeployIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type AgentDeployIndexInformer cache.TypedSharedIndexInformer[*apiskynomeshv1alpha1.AgentDeploy]

// AgentDeployHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for AgentDeploy.
type AgentDeployHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apiskynomeshv1alpha1.AgentDeploy]

// AgentDeployDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for AgentDeploy.
type AgentDeployDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apiskynomeshv1alpha1.AgentDeploy]

// AgentDeployFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for AgentDeploy.
type AgentDeployFilteringHandler = cache.TypedFilteringResourceEventHandler[*apiskynomeshv1alpha1.AgentDeploy]

// AgentDeployIndexers is a specialization of [cache.TypedIndexers] for AgentDeploy.
type AgentDeployIndexers = cache.TypedIndexers[*apiskynomeshv1alpha1.AgentDeploy]

// DeletedAgentDeploy is a specialization of [cache.DeletedObject] for AgentDeploy.
type DeletedAgentDeploy = cache.DeletedObject[*apiskynomeshv1alpha1.AgentDeploy]

type agentDeployInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAgentDeployInformer constructs a new informer for AgentDeploy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedAgentDeployInformer]).
func NewAgentDeployInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewAgentDeployInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedAgentDeployInformer constructs a new informer for AgentDeploy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedAgentDeployInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers AgentDeployIndexers) AgentDeployIndexInformer {
	return NewTypedAgentDeployInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredAgentDeployInformer constructs a new informer for AgentDeploy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredAgentDeployInformer]).
func NewFilteredAgentDeployInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedAgentDeployInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredAgentDeployInformer constructs a new informer for AgentDeploy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredAgentDeployInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers AgentDeployIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) AgentDeployIndexInformer {
	return NewTypedAgentDeployInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewAgentDeployInformerWithOptions constructs a new informer for AgentDeploy type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedAgentDeployInformerWithOptions]).
func NewAgentDeployInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedAgentDeployInformerWithOptions(client, namespace, options)
}

// NewTypedAgentDeployInformerWithOptions constructs a new informer for AgentDeploy type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedAgentDeployInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) AgentDeployIndexInformer {
	gvr := schema.GroupVersionResource{Group: "kynomesh.kyno.sh", Version: "v1alpha1", Resource: "agentdeploys"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apiskynomeshv1alpha1.AgentDeploy](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.KynomeshV1alpha1().AgentDeploys(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.KynomeshV1alpha1().AgentDeploys(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.KynomeshV1alpha1().AgentDeploys(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.KynomeshV1alpha1().AgentDeploys(namespace).Watch(ctx, opts)
			},
		}, client),
		&apiskynomeshv1alpha1.AgentDeploy{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *agentDeployInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedAgentDeployInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *agentDeployInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *agentDeployInformer) TypedInformer() AgentDeployIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiskynomeshv1alpha1.AgentDeploy](f.factory.InformerFor(&apiskynomeshv1alpha1.AgentDeploy{}, f.defaultInformer))
}

func (f *agentDeployInformer) Lister() kynomeshv1alpha1.AgentDeployLister {
	return kynomeshv1alpha1.NewAgentDeployLister(f.Informer().GetIndexer())
}

// ToTypedAgentDeployInformer converts an untyped informer into a TypedAgentDeployInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *AgentDeploy. If that is not the case, calling type-safe methods of the returned
// TypedAgentDeployInformer leads to runtime panics. A safer alternative is to pass
// around a TypedAgentDeployInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedAgentDeployInformer(informer AgentDeployInformer) TypedAgentDeployInformer {
	if informer, ok := informer.(TypedAgentDeployInformer); ok {
		return informer
	}
	return &agentDeployTypedInformerAdapter{informer}
}

type agentDeployTypedInformerAdapter struct {
	AgentDeployInformer
}

func (a *agentDeployTypedInformerAdapter) TypedInformer() AgentDeployIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiskynomeshv1alpha1.AgentDeploy](a.Informer())
}

// ToAgentDeployIndexInformer converts an untyped informer into a AgentDeployIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *AgentDeploy. If that is not the case, calling type-safe methods of the returned
// AgentDeployIndexInformer leads to runtime panics. A safer alternative is to pass
// around a AgentDeployIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToAgentDeployIndexInformer(informer cache.SharedIndexInformer) AgentDeployIndexInformer {
	if informer, ok := informer.(AgentDeployIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apiskynomeshv1alpha1.AgentDeploy](informer)
}
