/*
Copyright 2026 The Kynoproj Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiskynomeshv1alpha1 "github.com/kynoproj/kynomesh/pkg/apis/kynomesh/v1alpha1"
	versioned "github.com/kynoproj/kynomesh/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kynoproj/kynomesh/pkg/client/informers/externalversions/internalinterfaces"
	kynomeshv1alpha1 "github.com/kynoproj/kynomesh/pkg/client/listers/kynomesh/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AgentSetInformer provides access to a shared informer and lister for
// AgentSets. Prefer using the type-safe variant (see [TypedAgentSetInformer]).
type AgentSetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() kynomeshv1alpha1.AgentSetLister
}

// TypedAgentSetInformer provides access to a shared informer and lister for
// AgentSets, including the type-safe TypedInformer variant.
// It is a superset of AgentSetInformer.
type TypedAgentSetInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() AgentSetIndexInformer
	Lister() kynomeshv1alpha1.AgentSetLister
}

// AgentSetIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type AgentSetIndexInformer cache.TypedSharedIndexInformer[*apiskynomeshv1alpha1.AgentSet]

// AgentSetHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for AgentSet.
type AgentSetHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apiskynomeshv1alpha1.AgentSet]

// AgentSetDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for AgentSet.
type AgentSetDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apiskynomeshv1alpha1.AgentSet]

// AgentSetFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for AgentSet.
type AgentSetFilteringHandler = cache.TypedFilteringResourceEventHandler[*apiskynomeshv1alpha1.AgentSet]

// AgentSetIndexers is a specialization of [cache.TypedIndexers] for AgentSet.
type AgentSetIndexers = cache.TypedIndexers[*apiskynomeshv1alpha1.AgentSet]

// DeletedAgentSet is a specialization of [cache.DeletedObject] for AgentSet.
type DeletedAgentSet = cache.DeletedObject[*apiskynomeshv1alpha1.AgentSet]

type agentSetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAgentSetInformer constructs a new informer for AgentSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedAgentSetInformer]).
func NewAgentSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewAgentSetInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedAgentSetInformer constructs a new informer for AgentSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedAgentSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers AgentSetIndexers) AgentSetIndexInformer {
	return NewTypedAgentSetInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredAgentSetInformer constructs a new informer for AgentSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredAgentSetInformer]).
func NewFilteredAgentSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedAgentSetInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredAgentSetInformer constructs a new informer for AgentSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredAgentSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers AgentSetIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) AgentSetIndexInformer {
	return NewTypedAgentSetInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewAgentSetInformerWithOptions constructs a new informer for AgentSet type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedAgentSetInformerWithOptions]).
func NewAgentSetInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedAgentSetInformerWithOptions(client, namespace, options)
}

// NewTypedAgentSetInformerWithOptions constructs a new informer for AgentSet type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedAgentSetInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) AgentSetIndexInformer {
	gvr := schema.GroupVersionResource{Group: "kynomesh.kyno.sh", Version: "v1alpha1", Resource: "agentsets"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apiskynomeshv1alpha1.AgentSet](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.KynomeshV1alpha1().AgentSets(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.KynomeshV1alpha1().AgentSets(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.KynomeshV1alpha1().AgentSets(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.KynomeshV1alpha1().AgentSets(namespace).Watch(ctx, opts)
			},
		}, client),
		&apiskynomeshv1alpha1.AgentSet{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *agentSetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedAgentSetInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *agentSetInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *agentSetInformer) TypedInformer() AgentSetIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiskynomeshv1alpha1.AgentSet](f.factory.InformerFor(&apiskynomeshv1alpha1.AgentSet{}, f.defaultInformer))
}

func (f *agentSetInformer) Lister() kynomeshv1alpha1.AgentSetLister {
	return kynomeshv1alpha1.NewAgentSetLister(f.Informer().GetIndexer())
}

// ToTypedAgentSetInformer converts an untyped informer into a TypedAgentSetInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *AgentSet. If that is not the case, calling type-safe methods of the returned
// TypedAgentSetInformer leads to runtime panics. A safer alternative is to pass
// around a TypedAgentSetInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedAgentSetInformer(informer AgentSetInformer) TypedAgentSetInformer {
	if informer, ok := informer.(TypedAgentSetInformer); ok {
		return informer
	}
	return &agentSetTypedInformerAdapter{informer}
}

type agentSetTypedInformerAdapter struct {
	AgentSetInformer
}

func (a *agentSetTypedInformerAdapter) TypedInformer() AgentSetIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiskynomeshv1alpha1.AgentSet](a.Informer())
}

// ToAgentSetIndexInformer converts an untyped informer into a AgentSetIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *AgentSet. If that is not the case, calling type-safe methods of the returned
// AgentSetIndexInformer leads to runtime panics. A safer alternative is to pass
// around a AgentSetIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToAgentSetIndexInformer(informer cache.SharedIndexInformer) AgentSetIndexInformer {
	if informer, ok := informer.(AgentSetIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apiskynomeshv1alpha1.AgentSet](informer)
}
