apiVersion: v1
kind: ConfigMap
metadata:
  name: kynomesh-cmd-params-config
data:
  ### Whether to run the controller in namespaced scope, defaults to false.
  # namespaced: "false"
  #
  ### The namespace that the controller watches when "namespaced" is true.
  # managed.namespace: kynomesh-system
  #
  ### Whether to disable leader election for the controller, defaults to false
  # controller.leader.election.disabled: "false"
  #
  ### The duration that non-leader candidates will wait to force acquire leadership.
  #   This is measured against time of last observed ack. Default is 15 seconds.
  #   The configuration has to be: lease.duration > lease.renew.deadline > lease.renew.period
  # controller.leader.election.lease.duration: 15s
  #
  ### The duration that the acting controlplane will retry refreshing leadership before giving up.
  #   Default value is 10 seconds.
  #   The configuration has to be: lease.duration > lease.renew.deadline > lease.renew.period
  # controller.leader.election.lease.renew.deadline: 10s
  #
  ### The duration the LeaderElector clients should wait between tries of actions, which means every
  #   this period of time, it tries to renew the lease. Default is 2 seconds.
  #   The configuration has to be: lease.duration > lease.renew.deadline > lease.renew.period
  # controller.leader.election.lease.renew.period: 2s
