/*
Copyright 2026 The Kynoproj Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	kynomeshv1alpha1 "github.com/kynoproj/kynomesh/pkg/apis/kynomesh/v1alpha1"
	scheme "github.com/kynoproj/kynomesh/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AgentSetsGetter has a method to return a AgentSetInterface.
// A group's client should implement this interface.
type AgentSetsGetter interface {
	AgentSets(namespace string) AgentSetInterface
}

// AgentSetInterface has methods to work with AgentSet resources.
type AgentSetInterface interface {
	Create(ctx context.Context, agentSet *kynomeshv1alpha1.AgentSet, opts v1.CreateOptions) (*kynomeshv1alpha1.AgentSet, error)
	Update(ctx context.Context, agentSet *kynomeshv1alpha1.AgentSet, opts v1.UpdateOptions) (*kynomeshv1alpha1.AgentSet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, agentSet *kynomeshv1alpha1.AgentSet, opts v1.UpdateOptions) (*kynomeshv1alpha1.AgentSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kynomeshv1alpha1.AgentSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*kynomeshv1alpha1.AgentSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kynomeshv1alpha1.AgentSet, err error)
	AgentSetExpansion
}

// agentSets implements AgentSetInterface
type agentSets struct {
	*gentype.ClientWithList[*kynomeshv1alpha1.AgentSet, *kynomeshv1alpha1.AgentSetList]
}

// newAgentSets returns a AgentSets
func newAgentSets(c *KynomeshV1alpha1Client, namespace string) *agentSets {
	return &agentSets{
		gentype.NewClientWithList[*kynomeshv1alpha1.AgentSet, *kynomeshv1alpha1.AgentSetList](
			"agentsets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kynomeshv1alpha1.AgentSet { return &kynomeshv1alpha1.AgentSet{} },
			func() *kynomeshv1alpha1.AgentSetList { return &kynomeshv1alpha1.AgentSetList{} },
		),
	}
}
