/*
Copyright 2026 The Kynoproj Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	kynomeshv1alpha1 "github.com/kynoproj/kynomesh/pkg/apis/kynomesh/v1alpha1"
	scheme "github.com/kynoproj/kynomesh/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AgentDeploysGetter has a method to return a AgentDeployInterface.
// A group's client should implement this interface.
type AgentDeploysGetter interface {
	AgentDeploys(namespace string) AgentDeployInterface
}

// AgentDeployInterface has methods to work with AgentDeploy resources.
type AgentDeployInterface interface {
	Create(ctx context.Context, agentDeploy *kynomeshv1alpha1.AgentDeploy, opts v1.CreateOptions) (*kynomeshv1alpha1.AgentDeploy, error)
	Update(ctx context.Context, agentDeploy *kynomeshv1alpha1.AgentDeploy, opts v1.UpdateOptions) (*kynomeshv1alpha1.AgentDeploy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, agentDeploy *kynomeshv1alpha1.AgentDeploy, opts v1.UpdateOptions) (*kynomeshv1alpha1.AgentDeploy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kynomeshv1alpha1.AgentDeploy, error)
	List(ctx context.Context, opts v1.ListOptions) (*kynomeshv1alpha1.AgentDeployList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kynomeshv1alpha1.AgentDeploy, err error)
	AgentDeployExpansion
}

// agentDeploys implements AgentDeployInterface
type agentDeploys struct {
	*gentype.ClientWithList[*kynomeshv1alpha1.AgentDeploy, *kynomeshv1alpha1.AgentDeployList]
}

// newAgentDeploys returns a AgentDeploys
func newAgentDeploys(c *KynomeshV1alpha1Client, namespace string) *agentDeploys {
	return &agentDeploys{
		gentype.NewClientWithList[*kynomeshv1alpha1.AgentDeploy, *kynomeshv1alpha1.AgentDeployList](
			"agentdeploys",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kynomeshv1alpha1.AgentDeploy { return &kynomeshv1alpha1.AgentDeploy{} },
			func() *kynomeshv1alpha1.AgentDeployList { return &kynomeshv1alpha1.AgentDeployList{} },
		),
	}
}
