apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - https://raw.githubusercontent.com/kynoproj/kynomesh/refs/heads/main/docs/user-guide/reference/kustomize/kynomesh-transformer-config.yaml

namePrefix: my-

resources:
  - my-agentset.yaml

configMapGenerator:
  - literals:
      - FOO=BAR
    name: my-cm

secretGenerator:
  - literals:
      - password=Pa5SW0rD
    name: my-secret

labels:
  - includeSelectors: true
    pairs:
      foo: bar

commonAnnotations:
  foo: bar

images:
  - name: my-worker-image
    newTag: my-version
